#!/bin/bash

# Usage: new-devguide <branch-name>
#
# Script to create a new branch of the Python Developer's Guide.
#
# Also makes the Docs.
#
# This script assumes it is run from the following directory structure:
#
# <cwd>
#     main/
#     branches/

pushd main
hg pull
hg update
popd
hg clone main/ branches/$1
pushd branches/$1
touch NOTES.txt
mate .
make html
open _build/html/index.html
