#!/bin/bash

# Usage: new-python <branch-name>
#
# Script to create a new Python branch.
#
# Also builds Python and makes the Docs.
#
# This script assumes it is run from the following directory structure:
#
# <cwd>
#     main/
#     branches/

pushd main
hg pull
hg update
popd
hg clone main/ branches/$1
pushd branches/$1
touch NOTES.txt
mate .
./configure --with-pydebug && make -j2
pushd Doc
make html
open build/html/index.html
popd
