#!/bin/bash

# Usage: branch-python <branch-name>
#
# Script to create a new Python branch.
#
# Also builds Python and makes the Docs.
#
# This script assumes it is run from the following directory structure:
#
# <cwd>
#     main/
#     branches/

cd main
hg pull
hg update
cd ..
hg clone main/ branches/$1
cd branches/$1
touch NOTES.txt
mate .
./configure --with-pydebug && make -j2
cd Doc
make html
open build/html/index.html
cd ..
